### ISSUE TITLE
Impossible to close "Download file" windows

### ISSUE THREAD

**Issue by sirio81** [OpenMediaVault-Plugin-Developers/openmediavault-jdownloader#1]
Hi, I'm running omv 1.0.9.
I pressed the button "download" of a torrent and the brower is showing the "Download file" windows but the button "Close" doesn't work, not even once the download has ended.

Firefox 24.5.0

**Comment by cptjhmiller** [comment]
any chance you can post a screen shot, I don't use it myself and I am unclear as to what you mean.

I take it the torrent downloads ok but something stays that is not meant to?
