### ISSUE TITLE
Update/ fresh install gets stuck

### ISSUE THREAD

**Issue by ghost** [OpenMediaVault-Plugin-Developers/openmediavault-jdownloader#2]
On my system an update or a fresh installation is not possible. The process keeps hanging. After 30min i cancelled the update/install and i got an error with "Failed to connect to socket: No such file or directory" when webgui of OMV was reloading. I had to uninstall jdownloader via SSH.

Some more informations:

![install](https://cloud.githubusercontent.com/assets/10474718/5691279/ba985754-98be-11e4-9288-b36a5a63245b.jpg)
![system](https://cloud.githubusercontent.com/assets/10474718/5691280/babb32a6-98be-11e4-8025-cce2753c1880.jpg)

**Comment by cptjhmiller** [comment]
It has been fixed in next release
