### ISSUE TITLE
Change logging behaviour

### ISSUE THREAD

**Issue by Flachzange** [OpenMediaVault-Plugin-Developers/openmediavault-jdownloader#5]
JDownloader is very excessive when it comes to logging. When started by systemd all logging goes to /var/log/daemon.log, which is a lot.

I added a `StandardOutput=null` to the service file but it's probably better to have a separate log file. However, piping the output at the end of the command did not work for me.

```
[Unit]
Description=jdownloader
After=network.target

[Service]
WorkingDirectory=/opt/jdownloader/
User=jdownloader
Group=users
Type=simple
UMask=000
ExecStart=/usr/bin/java -Djava.awt.headless=true -jar JDownloader.jar
RestartSec=15
Restart=always
StandardOutput=null

[Install]
WantedBy=multi-user.target
```

**Comment by cptjhmiller** [comment]
I have never really looked at the logging, do you think it is best to disable it like you have above or have an option to disable it via the plugin page?

**Comment by Flachzange** [comment]
Ideally, I would prefer a setting in the plugin page where I could specify an optional log file path. Alternatively, the log file path could be predefined and the plugin page is just there to enable it (default off). The log output shouldn't go to the daemon.log

**Comment by cptjhmiller** [comment]
I think, to keep things simple, it would be best to have an "Enable logging" option.
A predefined location would be better then giving the user a choice as to where to store the logs.

**Comment by cptjhmiller** [comment]
I can enable/disable the default logging but i can not change the logging destination to anything.
I had hoped that at least i could use a > to redirect the log but even that does not work.

Maybe something alone these lines?
https://board.jdownloader.org/showpost.php?p=87231&postcount=26

**Comment by Flachzange** [comment]
What seems to work ist:

`ExecStart=/bin/sh -c '/usr/bin/java -Djava.awt.headless=true -jar JDownloader.jar > /var/log/jdownloader.log 2>&1'`

**Comment by cptjhmiller** [comment]
Thanks but I did find that out just after i posted.
I have now almost finished the next version for OMV 3.0.15.

I need to check how the upgrade works when going from earlier versions of OMV as OMV 3.0.15 changed quite a lot.

**Comment by cptjhmiller** [comment]
New version coming soon, open a new issue if problem persists.
